name: Sync to Aliyun ECS

on:
  push:
    branches:
      - main # 或者你的默认分支名

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: SFTP Deploy
      # You may pin to the exact commit or the version.
      # uses: wlixcc/SFTP-Deploy-Action@da88a4dbe95286266bbac3c0b2b8284048d20c8f
      uses: wlixcc/SFTP-Deploy-Action@v1.2.4
      with:
        # username
        username: ${{secrets.USERNAME}}
        # your sftp server
        server: ${{secrets.IPADDRESS}}
        # your sftp server port, default to 22
        port: 22
        # you can copy private_key from your *.pem file, keep format
        ssh_private_key: ${{secrets.SSH_KEY}}
        # will put all file under this path
        local_path: ./*
        # files will copy to under remote_path
        remote_path: /home/zzstar/nginx/html/
        # connection via sftp protocol only
        sftp_only: true
        # sftp args
        #sftpArgs: # optional
        # This operation will delete all files in the remote path before upload. Please be careful set this to true
        #delete_remote_files: # optional
        # SSH passsword，If a password is set, the secret key pair is ignored
        # password: ${{secrets.PASSWORD}}
          
